# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-13 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='WebcategorySub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcategory_id', models.IntegerField(choices=[(100, '设计导航'), (101, '设计素材'), (102, '设计理论'), (103, '设计收藏'), (200, 'python'), (201, 'javascript'), (202, 'html5'), (203, 'css3'), (204, 'css3'), (205, 'git'), (206, 'vue'), (207, 'node'), (208, 'angular'), (209, 'react'), (210, 'linux'), (211, 'php'), (212, 'c'), (213, 'mysql'), (300, '3dMax'), (301, 'AE'), (400, '游戏'), (401, '其他')])),
            ],
        ),
        migrations.CreateModel(
            name='WebPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webname', models.CharField(max_length=32)),
                ('webdescribe', models.CharField(max_length=32)),
                ('webtab', models.CharField(max_length=32)),
                ('webclass_id', models.IntegerField(choices=[(1, '设计'), (2, '代码'), (3, '模型'), (4, '其他')])),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='wid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.WebPage'),
        ),
        migrations.AddField(
            model_name='users',
            name='wsid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.WebcategorySub'),
        ),
    ]
